### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by Migz93** [Migz93/lidarr-download-automation#25]
A few people have mentioned that they'd like docker support. Raising this to track it.
It's on the list of things to do, just waiting for @RandomNinjaAtk to get to a stable state with his wonderful behind the scenes work on the script and then need to get the wiki up to an acceptable standard.

**Comment by RandomNinjaAtk** [comment]
I'm not sure what this is specifically requesting, when it can already be used in a docker container.

**Comment by Migz93** [comment]
Discusssed with RandomNinjaAtk, initial comment isn't clear.

The script itself works with no issues inside existing containers, i.e you could run it within linuxserver/lidarr with the correct know how.
This issue is specifically around creating our own docker image that just runs the script every x hours.

**Comment by orsomething1030** [comment]
The docker container willfarrell/crontab works for me.  Couldn't figure out how to get cron working in the linuxserver/lidarr container with a /config/custom-cont-init.d custom script.

**Comment by RandomNinjaAtk** [comment]
@orsomething1030 Is it working via cron using d-fi or smloadr? I am not able to get it to work with d-fi using cron, smloadr works fine though. So just curious...

**Comment by RandomNinjaAtk** [comment]
cron issue is resolved in new version
