### ISSUE TITLE
Running with Lidarr in a docker

### ISSUE THREAD

**Issue by monkeyhat** [Migz93/lidarr-download-automation#28]
This is probably a stupid question (sorry) but I run Lidarr in a docker container. This means it doesn't have full access to the file system. So when the script tells Lidarr to pick up a downloaded album from, say "/volume1/unsorted/unsortedmusic/artist", Lidarr can't see that folder. 

There's an option in Lidarr to work around this, where you can set directory aliases (so it'll look for "/volume1/Unsorted/unsortedmusic/" as "/Unsorted/unsortedmusic/" for example.) But this only works for download clients, and the smloadr script isn't treated in the same way. 

Would it be possible to add a config option to set a second path, so when the post-processing request goes to Lidarr it's sent with a different path name?

Something like: 

DownloadDir="/volume1/Unsorted/unsortedmusic/"
LidarrDownloadDir="/Unsorted/unsortedmusic/"

Or is it something I can hard code into my version of the script? I assume I could change something in the below, but those sed commands are way beyond my limited bash skills!

`LidarrProcess(){
	logit "Sending to Lidarr for post processing"
	dlloc=($(find "${DownloadDir}" -maxdepth 1 -type d -not -path "${DownloadDir}"))
	for d in "${dlloc[@]}"; do
		if [ "${EnableWSLMode}" = True ];then
			dwrap=($( echo "${d}"|sed -e 's/mnt\///' -e 's/^\///' -e 's/^./\0:/' -e 's/\//\\\\/g' -e 's/^/\"/g' -e 's/$/\"/g'))
		else
			dwrap=($( echo "${d}"|sed -e 's/^/\"/g' -e 's/$/\"/g'))
		fi
		LidarrProcessIt=$(curl -s "$LidarrUrl/api/v1/command" --header "X-Api-Key:"${LidarrApiKey} --data '{"name":"DownloadedAlbumsScan", "path":'"${dwrap}"'}' );
	done
	sleep 3s
}`

Thanks in advance for your help - and thanks for tm the great script!

**Comment by RandomNinjaAtk** [comment]
If your paths are setup correctly it will work in the docker container from linuxserver without any script modifications, that's how I use and test it

**Comment by monkeyhat** [comment]
Thanks for the reply! How do you mean if my paths are set up correctly? In Lidarr or in the script config? 

I'm using the Linuxserver.io container too, so it's clearly something I'm overlooking. 

At present I just get a lot of "DownloadAlbumsCommandService|Folder / file specified for import scan [/volume1/Unsorted/unsortedmusic/artist] doesn't exist" lines in my Lidarr log.

I've made sure "/volume1/Unsorted/unsortedmusic/" is mapped to the container-accessible "/Unsorted/unsortedmusic/" in Lidarr (though as I mentioned, I think this might only apply to download clients.)

I can't think of any other way to set the paths.

**Comment by RandomNinjaAtk** [comment]
So its best to run the script from within the container, and the paths should be lined up with what the container can see, as far as file structure.

So the best way to do that is from the container CLI. So you need to use a command like:

"docker exec -it lidarr /bin/bash" - replace lidarr with the actual container name if it is not that.
(the command lets you enter the docker containers CLI)

So an example would be if your mapped volumes in the container are:

/config
/music

Your script config file should also be set to 

/config or /music

And if the script is stored in /config, to run the script you will just need to:

```
docker exec -it lidarr /bin/bash
cd /config
bash <scriptname>
```

To execute it, then lidarr will be able to see the files correctly.

**Comment by RandomNinjaAtk** [comment]
this works within docker
