### ISSUE TITLE
iconv position error workaround

### ISSUE THREAD

**Issue by ztomer** [Migz93/lidarr-download-automation#30]
I got several "iconv illegal input sequence" errors - basically, the the queried results were not UTF-8
Following this post, I was able work around, this problem

https://unix.stackexchange.com/questions/141539/iconv-illegal-input-sequence-why

This is how the code looks in my patched version:
```
alias ICONV_CMD_LATIN1="iconv -f latin1 -t ascii//TRANSLIT"
alias ICONV_CMD_UTF8="iconv -f UTF-8 -t ASCII/TRANSLIT"

ICONV_CMD=${ICONV_CMD_LATIN1}
```

The caveat here is that using latin1 will probably not work for non-latin1 encoding, so the correct solution is probably to either use it as a fallback when this error is detected, or as a user option (force-ascii?)

**Comment by RandomNinjaAtk** [comment]
Feel free to make a pull request so we can review for merging the fix.
